import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";

const pretendard = localFont({
    src: "./pretendard.woff2",
    variable: "--font-pretendard",
    display: "swap",
    weight: "45 920",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="kr">
            <body className={`${pretendard.variable} font-pretendard  bg-neutral-900`}>
                <NextTopLoader color="#2dd4bf" />
                {children}
            </body>
        </html>
    );
}
